/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:3344d138-07fa-472b-b698-7f3178230bb3",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_xAm7QEeSe",
    "aws_user_pools_web_client_id": "3q99bo9sbst074h797m2k0dh0f",
    "oauth": {}
};


export default awsmobile;
